# Generated by Django 3.2.8 on 2021-10-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.TextField()),
                ('edges', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RearrangementProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_isomorphism', models.TextField()),
                ('move_type', models.SmallIntegerField(choices=[(0, 'no moves'), (1, 'tail moves'), (2, 'head moves'), (3, 'rSPR moves')], verbose_name='move type')),
                ('vertical_allowed', models.BooleanField(default=False)),
                ('network1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems1', to='phylofun.network')),
                ('network2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems2', to='phylofun.network')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('isomorphism', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='phylofun.rearrangementproblem')),
            ],
        ),
    ]
