# Generated by Django 3.2.11 on 2022-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0002_auto_20211021_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionModel',
            new_name='RearrangementSolutionModel',
        ),
    ]
