# Generated by Django 3.2.11 on 2022-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0003_rename_solutionmodel_rearrangementsolutionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmodel',
            name='edges',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='labels',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='nodes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rearrangementproblemmodel',
            name='move_type',
            field=models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'TAIL'), (2, 'HEAD'), (3, 'RSPR')], verbose_name='move type'),
        ),
        migrations.AlterField(
            model_name='rearrangementsolutionmodel',
            name='isomorphism',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rearrangementsolutionmodel',
            name='sequence',
            field=models.JSONField(),
        ),
    ]
