# Generated by Django 3.2.11 on 2022-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0004_auto_20220214_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rearrangementproblemmodel',
            name='move_type',
            field=models.CharField(choices=[('NONE', 'no moves'), ('TAIL', 'tail moves'), ('HEAD', 'head moves'), ('RSPR', 'rSPR moves')], default='NONE', max_length=4, verbose_name='move type'),
        ),
    ]
