# Generated by Django 3.2.12 on 2022-03-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0005_alter_rearrangementproblemmodel_move_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmodel',
            name='binary',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='classes',
            field=models.CharField(choices=[('tree-child', 'tree-child'), ('tree-based', 'tree-based'), ('orchard', 'orchard'), ('stack-free', 'stack-free')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='number_of_leaves',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='number_of_roots',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='edges',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='nodes',
            field=models.JSONField(default=list),
        ),
    ]
