# Generated by Django 3.2.12 on 2022-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0007_auto_20220320_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmodel',
            name='node_positions',
            field=models.JSONField(default=list),
        ),
    ]
