# Generated by Django 3.2.12 on 2022-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylofun', '0008_networkmodel_node_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rearrangementproblemmodel',
            name='goal_length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
