default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3'
  hooks:
  - id: isort
    exclude: 'settings'
- repo: https://github.com/ambv/black
  rev: 21.10b0
  hooks:
  - id: black
    exclude: 'migrations*|urls*|setup.py'
    args: [--line-length=79]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: flake8
    # NB The "exclude" setting in setup.cfg is ignored by pre-commit
    exclude: 'migrations*|urls*|settings*'
