default_language_version:
  python: python3
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    exclude: 'migrations*|urls*|settings*|setup.py'
    args: [--line-length=79]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: flake8
    # NB The "exclude" setting in setup.cfg is ignored by pre-commit
    exclude: 'migrations*|urls*|settings*|hydra_core/utils/turtleurbanclasses.py'
